package api.contacts;
import api.contacts.Contact;
import io.swagger.annotations.ApiOperation;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller // This means that this class is a Controller
@RequestMapping(path = "/contacts") // This means URL's start with /contact (after Application path)
public class ContactResource {
	@Autowired // This means to get the bean called contactRepository
	// Which is auto-generated by Spring, we will use it to handle the data
	private ContactRepository contactRepository;

	@ApiOperation("Return all contacts")
	@GetMapping("")
	public @ResponseBody Iterable<Contact> getAllcontacts() {
		// This returns a JSON or XML with the contacts
		return contactRepository.findAll();
	}
}
