package api.planning;

import api.planning.PlanningView;
import io.swagger.annotations.ApiOperation;

import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller // This means that this class is a Controller
@RequestMapping(path = "/plannings") // This means URL's start with /contact (after Application path)
public class PlanningResource {
	@Autowired // This means to get the bean called contactRepository
	// Which is auto-generated by Spring, we will use it to handle the data
	private PlanningViewRepository planningViewRepository;

	@ApiOperation("Return all plannings")
	@GetMapping("")
	public @ResponseBody ResponseEntity<Iterable<PlanningView>> getAllcontacts() {
		// This returns a JSON or XML with the contacts
		Iterable<PlanningView> list = planningViewRepository.findAll();
		return new ResponseEntity<Iterable<PlanningView>>(list, HttpStatus.OK);
	}
}
